apiVersion: skaffold/v3
kind: Config

build:
  artifacts:
    []
    # TODO add your docker files here.
    # For more info checkout the skaffold docs https://skaffold.dev/docs/references/yaml/?version=v3
    # Example
    # - image: example
    #   context: ./docker/build/context
    #   docker:
    #     dockerfile: Dockerfile

deploy:
  helm:
    releases:
      - name: "{{ .PROJECT_NAME }}"
        chartPath: ./helm
        namespace: "{{ .PROJECT_NAME }}-dev"
        createNamespace: true
        valuesFiles:
          - ./helm/services.yaml
